### ISSUE TITLE
L6 wiki edit request

### ISSUE THREAD

**Issue by zyoa** [18-1-SKKU-OSS/2018-1-OSS-L6#1]
to Taewoo Jung

Plz edit with format to write
- Who translated what
- What his role was

until tonight

**Comment by EherSenaw** [comment]
@zyoa ,I will try to do such tasks as soon as possible, but please consider that we(our team) are all in hard-pressure of a lot to do.

**Comment by EherSenaw** [comment]
@zyoa , finished.
