### ISSUE TITLE
[Static Page] Finishing Static Page

### ISSUE THREAD

**Issue by EherSenaw** [18-1-SKKU-OSS/2018-1-OSS-L6#2]
@zyoa , make sure to end up the static page, please.

**Comment by zyoa** [comment]
'Jekyll' files seem to be unable to modify image css files
I will confirm and notice you.

**Comment by EherSenaw** [comment]
Thanks

**Comment by zyoa** [comment]
BJH presented another static page form! We are only going to need to make detailed context.

**Comment by EherSenaw** [comment]
....And we should do that today.
