### ISSUE TITLE
[Static Page] About adding Kotlin's short introduction

### ISSUE THREAD

**Issue by EherSenaw** [18-1-SKKU-OSS/2018-1-OSS-L6#5]
Will we add video or anything that would help listeners to understand what Kotlin project is? 
@zyoa @tsfo1489 @BJH9750

**Comment by tsfo1489** [comment]
I think that is good idea, But I don't know which video can explain kotlin in a short time

**Comment by EherSenaw** [comment]
How about imbedding Kotlin official web page?

**Comment by EherSenaw** [comment]
Added Kotlin official web page in imbedded mode: [check](https://18-1-skku-oss.github.io/2018-1-OSS-L6/#/2/2)

**Comment by EherSenaw** [comment]
@BJH9750 I want to make position of this post into the introduction part of full posts, can you help with that?

**Comment by BJH9750** [comment]
@EherSenaw Finish
