### ISSUE TITLE
[Static Page] How to change static page's title

### ISSUE THREAD

**Issue by tsfo1489** [18-1-SKKU-OSS/2018-1-OSS-L6#6]
The title of the static page is now "Interactive Presentation". It would be better to change this. So where can I change this part?
@18-1-SKKU-OSS/2018-1-oss-l6

**Comment by EherSenaw** [comment]
Dear @tsfo1489 , it's in /_includes/head.html, I temporally made it to "Jaewon Babo" to check.

**Comment by EherSenaw** [comment]
@tsfo1489 if you've checked, please close this one

**Comment by tsfo1489** [comment]
Thanks
